default:
    suites:
        ui_managing_articles:
            contexts:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.article
                - app.behat.context.setup.customer
                - app.behat.context.setup.admin_security

                - app.behat.context.transform.article
                - app.behat.context.transform.customer
                - app.behat.context.transform.shared_storage

                - app.behat.context.ui.backend.managing_articles
                - app.behat.context.ui.backend.notification
            filters:
                tags: "@managing_articles && @ui"
