default:
    suites:
        ui_managing_articles:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - App\Behat\Context\Setup\ArticleContext
                - App\Behat\Context\Setup\CustomerContext
                - App\Behat\Context\Setup\AdminSecurityContext

                - App\Behat\Context\Transform\ArticleContext
                - App\Behat\Context\Transform\CustomerContext
                - App\Behat\Context\Transform\SharedStorageContext

                - App\Behat\Context\Ui\Backend\ManagingArticlesContext
                - App\Behat\Context\Ui\Backend\NotificationContext
            filters:
                tags: "@managing_articles && @ui"
