services:
    _defaults:
        autowire: true
        tags: [sylius_fixtures.fixture]

    App\Fixture\AdminUserFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\AdminUserExampleFactory'

    App\Fixture\AppUserFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\AppUserExampleFactory'

    App\Fixture\ArticleFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\ArticleExampleFactory'

    App\Fixture\OAuthClientFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\OAuthClientExampleFactory'
