imports:
    - suites/ui/account/customer.yml
    - suites/ui/account/login.yml
    - suites/ui/article/managing_articles.yml
    - suites/ui/customer/managing_customers.yml
    - suites/ui/user/managing_administrators.yml
